spring.application.name=SpringBoot3.1.1
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url jdbc:mysql://localhost:3306/new_baza?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=Serkov16@


spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework=debug
logging.level.org.hibernate=debug





